name: Report an issue with docker-transmission-openvpn
description: Report an issue with docker-transmission-openvpn
title: ""
issue_body: true
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only.

        If you are requesting a [new feature][nf], please create a [new feature request][nf].
        If you are requesting new providers, please open a [feature request][fr] on our [Provider repo][fr].
        [nf]: https://github.com/haugene/docker-transmission-openvpn/issues/new?assignees=&labels=bug&template=feature_request.yml&title=
        [fr]: https://github.com/haugene/vpn-configs-contrib/issues
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    validations:
      required: true
    attributes:
      label: What is version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in the Configuration panel -> Info.
  - type: input
    attributes:
      label: What was the last working version of Home Assistant Core?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        If you don't know, you can find it in: Configuration panel -> Info.
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: input
    attributes:
      label: Integration causing the issue
      description: >
        The name of the integration, for example, Automation or Philips Hue.
  - type: input
    attributes:
      label: Link to integration documentation on our website
      placeholder: "https://www.home-assistant.io/integrations/..."
      description: |
        Providing a link [to the documentation][docs] help us categorizing the
        issue, while providing a useful reference at the same time.

        [docs]: https://www.home-assistant.io/integrations

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Example YAML snippet
      description: |
        If this issue has an example piece of YAML that can help reproducing this problem, please provide.
        This can be an piece of YAML from, e.g., an automation, script, scene or configuration.
      value: |
        ```yaml
        # Put your YAML below this line

        ```
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      value: |
        ```txt
        # Put your logs below this line

        ```
  - type: markdown
    attributes:
      value: |
        ## Additional information
  - type: markdown
    attributes:
      value: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
